### ISSUE TITLE
Can't use "watch" function on Linux

### ISSUE THREAD

**Issue by herosql** [ymzuiku/bike#2]
The error like this:

fs.js:1578
    throw new ERR_FEATURE_UNAVAILABLE_ON_PLATFORM('watch recursively');
    ^

TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
    at Object.watch (fs.js:1578:11)
    at Object.<anonymous> (/home/liliang/Documents/project/hpv-project-server/node_modules/airt/lib/index.js:94:8)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'ERR_FEATURE_UNAVAILABLE_ON_PLATFORM'
}

Maybe you can look at this link ‘ https://stackoverflow.com/questions/61806341/how-to-fix-the-feature-watch-recursively-is-unavailable-on-the-current-platform’  or 'https://nodejs.org/docs/latest/api/fs.html#fs_caveats'

**Comment by herosql** [comment]
I tried to switch the "node" version, but it didn't solve the problem

**Comment by ymzuiku** [comment]
已兼容linux: [#6688802f913](https://github.com/ymzuiku/bike/commit/6688802f913bee4a2c6651012c72ed1a6f15c73e)
获取 bike@0.6.5 或以上的版本即可
